# Development Frontend Dockerfile
FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]