name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server_ip: ["13.51.154.120", "51.21.229.211"]

    steps:
      - name: Deploy via SSH to ${{ matrix.server_ip }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ matrix.server_ip }} # Uses the IP from the matrix
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            cd BlurThatGuyProject

            git pull origin main

            docker compose -f docker-compose.prod.yml down

            docker image prune -af

            docker compose -f docker-compose.prod.yml up -d --build

            echo "Deployment to ${{ matrix.server_ip }} complete"